<?php

class Wp_Data_Append_Service {
	public static function get_labels() {
		return array(
			'we_result_id' => true,
			'we_estimated_annual_donations' => true,
			'we_gift_capacity' => true,
			'we_p2g_score' => true,
			'we_full_name' => true,
			'we_age' => true,
			'we_gender' => true,
			'we_address_1' => true,
			'we_address_2' => true,
			'we_address_3' => true,
			'we_total_property_count' => true,
			'we_total_real_estate_value' => true,
			'we_accredited_investor' => true,
			'we_networth' => true,
			'we_total_income' => true,
			'we_raw_result' => true,
			'td_raw_result' => true,
			'td_age' => true,
			'td_gender' => true,
			'td_zip' => true,
			'td_education' => true,
			'td_high_net_worth' => true,
			'td_household_income' => true,
			'td_home_market_value' => true,
			'td_home_owner_status' => true,
			'td_length_of_residence' => true,
			'td_marital_status' => true,
			'td_occupation' => true,
			'td_presence_of_children' => true,
			'td_interests' => true,
			'td_date_first_seen' => true,
			'td_popularity' => true,
			'td_velocity' => true,
			'td_month_last_open' => true,
			'we_maritalstatus' => true,
			'we_has_children' => true,
			'we_spouse_full_name' => true,
			'we_affiliation_inclination' => true,
			'we_influence_rating' => true,
			'we_planned_giving' => true,
			'we_charitable_donations' => true,
			'we_business_ownership' => true,
			'we_business_sales_volume' => true,
			'we_cash_on_hand' => true,
			'we_investable_assets' => true,
			'we_total_assets' => true,
			'we_total_stock' => true,
			'we_stock_holdings_direct' => true,
			'we_stock_holdings_indirect' => true,
			'we_total_pensions' => true,
			'we_vehicle_ownership' => true,
			'we_is_board_member' => true,
			'we_jobs' => true,
			'we_total_political_donations' => true,
			'we_request_args' => true
		    );
	}
}